version: '3'

services:

  database:
    image: mysql:5.7
    environment: 
      MYSQL_DATABASE: 'reservations'
      MYSQL_USER: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
   
  

  reservations:
    build: .
    restart: always
    depends_on:
      - 'database'
    ports: 
      - '3000:3000'
